# ==============================================================================
# Module: 01_qgam_modelling.R
# Description: Core modelling pipeline fitting qGAMs (tau = 0.5) to evaluate
# temporal and seasonal latitudinal shifts of neustonic organisms.
# Fits are saved as binary objects for subsequent visualisation.
# ==============================================================================

library(dplyr)
library(lubridate)
library(mgcv)
library(qgam)
library(gratia)

set.seed(1234)

# ------------------------------------------------------------------------------
# 1. GLOBAL SETTINGS & HYPERPARAMETERS
# ------------------------------------------------------------------------------
YEAR_MIN <- 2014
TAU_MED  <- 0.5
K_YDAY_GRID <- 4:15
K_YEAR_GRID <- 4:10
TOL <- 0.005

# Manual basis dimensions (k) established post grid-search optimisation
k_manual <- tibble::tribble(
  ~species,            ~ky, ~kt,
  "Physalia",           8,   9,
  "Velella",            6,   4,
  "Neutral Neuston",    5,   4
)

# ------------------------------------------------------------------------------
# 2. CORE FUNCTIONS
# ------------------------------------------------------------------------------
prep_data <- function(df, year_min = YEAR_MIN) {
  df |>
    mutate(
      # Transform temporal data into numeric vectors for the qGAM tensors
      yday        = yday(verbatimEventDate),
      decimalYear = decimal_date(verbatimEventDate)
    ) |>
    filter(year >= year_min)
}

fit_mqgam_median_fixedk <- function(data, ky, kt) {
  mqgam(
    decimalLatitude ~ s(yday, bs = "cc", k = ky) + s(decimalYear, bs = "tp", k = kt),
    qu   = c(TAU_MED),
    data = data
  )
}

extract_mq_smooth <- function(fit, tau, smooth_var){
  m_tau <- qdo(fit, qu = tau)
  intercept   <- coef(m_tau)[1]
  smooth_name <- paste0("s(", smooth_var, ")")
  
  smooth_estimates(m_tau, smooth = smooth_name) |>
    mutate(
      latitud_real  = .estimate + intercept,
      latitud_upper = .estimate + intercept + 2 * .se,
      latitud_lower = .estimate + intercept - 2 * .se,
      cuantil       = paste0("q", tau),
      variable      = smooth_var
    )
}

run_species <- function(raw_df, species_label, ky_fixed, kt_fixed, year_min = YEAR_MIN) {
  df <- prep_data(raw_df, year_min = year_min)
  mq_fit <- fit_mqgam_median_fixedk(df, ky = ky_fixed, kt = kt_fixed)
  
  effects_mq_all <- bind_rows(
    extract_mq_smooth(mq_fit, TAU_MED, "yday"),
    extract_mq_smooth(mq_fit, TAU_MED, "decimalYear")
  ) |>
    mutate(species = species_label)
  
  list(
    data          = df,
    mq_fit        = mq_fit,
    effects_yday  = effects_mq_all |> filter(variable == "yday"),
    effects_dyear = effects_mq_all |> filter(variable == "decimalYear")
  )
}

# ------------------------------------------------------------------------------
# 3. EXECUTION AND DATA EXPORT
# ------------------------------------------------------------------------------
# Load raw processed data dynamically generated by 00_preprocess.R
eurobs_physalia       <- readRDS("data/processed/eurobs_physalia.rds")
eurobs_velella        <- readRDS("data/processed/eurobs_velella.rds")
eurobs_neutralNeuston <- readRDS("data/processed/eurobs_neutralNeuston.rds")

message("Data loaded successfully. Commencing model fitting...")

# Execute models based on the predefined basis dimensions
res_physalia <- run_species(eurobs_physalia, "Physalia", 8, 6)
res_velella <- run_species(eurobs_velella, "Velella", 7, 4)
res_neutral <- run_species(eurobs_neutralNeuston, "Neutral Neuston", 5, 4)

# Consolidate results for plotting
df_all <- bind_rows(
  res_physalia$data |> mutate(species = "Physalia"),
  res_velella$data  |> mutate(species = "Velella"),
  res_neutral$data  |> mutate(species = "Neutral Neuston")
)

effects_yday_all <- bind_rows(res_physalia$effects_yday, res_velella$effects_yday, res_neutral$effects_yday)
effects_year_all <- bind_rows(res_physalia$effects_dyear, res_velella$effects_dyear, res_neutral$effects_dyear)

# Export consolidated dataframes for plotting to avoid re-fitting models
saveRDS(df_all, "data/processed/modelling_df_all.rds")
saveRDS(effects_yday_all, "data/processed/modelling_effects_yday.rds")
saveRDS(effects_year_all, "data/processed/modelling_effects_year.rds")
saveRDS(list(res_physalia, res_velella, res_neutral), "data/processed/mqgam_models.rds")

message("Modelling complete. Mathematical outputs saved to 'data/processed/'.")