# ==============================================================================
# @file:    02_qgam_figures.r
# @author:  Yago Iván-Baragaño (ivanyago@uniovi.es)
# @funding: Severo Ochoa Ph.D. program (Principado de Asturias, NAC-AT-PUB-ASV-2025 BP24-109)
# @cite:    
# @brief:   Visualisation module for qGAMs plots
# Seasonal, historical, and biological Hovmöller diagrams
# ==============================================================================

library(dplyr)
library(ggplot2)
library(sf)
library(rnaturalearth)
library(patchwork)
library(qgam)
library(lubridate)

# ------------------------------------------------------------------------------
# 1. LOAD PRE-COMPUTED MODEL DATA
# ------------------------------------------------------------------------------
# Ingest the static mathematical outputs generated by 01_qgam_modelling.R
df_all           <- readRDS("data/processed/modelling_df_all.rds")
effects_yday_all <- readRDS("data/processed/modelling_effects_yday.rds")
effects_year_all <- readRDS("data/processed/modelling_effects_year.rds")

# ------------------------------------------------------------------------------
# 2. GLOBAL AESTHETIC CONFIGURATIONS
# ------------------------------------------------------------------------------
col_map <- c(
  "Physalia"         = "#7570b3",
  "Velella"          = "#1b9e77",
  "Neutral Neuston"  = "#d95f02"
)

shape_map <- c(
  "Physalia"         = 15,
  "Velella"          = 16,
  "Neutral Neuston"  = 17
)

# Standardised temporal breaks
month_breaks <- yday(as.Date(paste0("2020-", 1:12, "-01")))
month_labels <- month.abb

# Define visual limits for historical plotting to prevent unwarranted extrapolation
x_start <- 2014
x_end   <- max(df_all$decimalYear, na.rm = TRUE)

# Minimal theme template for base plots (No facets)
theme_base_plot <- theme_minimal(base_size = 20) +
  theme(
    panel.grid.major.x = element_line(colour = "grey85", linewidth = 0.5),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_line(colour = "grey85", linewidth = 0.5),
    panel.grid.minor.y = element_line(colour = "grey90", linewidth = 0.5, linetype = "dashed"),
    axis.line.x = element_line(color = "black", linewidth = 0.8),
    axis.line.y = element_line(color = "black", linewidth = 0.8),
    axis.ticks = element_line(color = "black", linewidth = 0.6),
    axis.ticks.length = unit(0.18, "cm"),
    panel.border = element_blank(),
    legend.position = c(0.15, 0.9),
    legend.background = element_rect(fill = scales::alpha("white", 0.5), color = "black", linewidth = 0.3),
    legend.title = element_blank(),
    axis.title = element_text(face = "bold"),
    axis.text  = element_text(color = "black")
  )

# ------------------------------------------------------------------------------
# 3. CONSTRUCT BASE PLOTS (OVERLAID SPECIES)
# ------------------------------------------------------------------------------
# --- Seasonal (yday) ---
seasonal_plot_base <- ggplot() +
  geom_point(data = df_all, aes(x = yday, y = decimalLatitude, color = species, shape = species, fill = species), alpha = 0.2, size = 2) +
  geom_ribbon(data = effects_yday_all, aes(x = yday, ymin = latitud_lower, ymax = latitud_upper, fill = species), alpha = 0.2, color = NA) +
  geom_line(data = effects_yday_all, aes(x = yday, y = latitud_real, color = species), linewidth = 1.5) +
  scale_color_manual(values = col_map) +
  scale_fill_manual(values = col_map) +
  scale_shape_manual(values = shape_map) +
  scale_x_continuous(breaks = month_breaks, labels = month_labels, expand = c(0, 0), name = "") +
  scale_y_continuous(name = "Latitude (°N)") +
  guides(fill = "none", color = guide_legend(override.aes = list(alpha = 1, linewidth = 1, size = 4))) +
  theme_base_plot

# --- Historical (decimalYear) ---
historical_plot_base <- ggplot() +
  geom_ribbon(data = effects_year_all, aes(x = decimalYear, ymin = latitud_lower, ymax = latitud_upper, fill = species), alpha = 0.2, color = NA) +
  geom_line(data = effects_year_all, aes(x = decimalYear, y = latitud_real, color = species), linewidth = 1.5) +
  geom_point(data = df_all, aes(x = decimalYear, y = decimalLatitude, color = species, shape = species, fill = species), alpha = 0.15, size = 2) +
  scale_color_manual(values = col_map) +
  scale_fill_manual(values = col_map) +
  scale_shape_manual(values = shape_map) +
  scale_x_continuous(name = "", breaks = seq(floor(x_start), ceiling(x_end), by = 1), expand = c(0, 0)) +
  scale_y_continuous(name = "Latitude (°N)") +
  coord_cartesian(xlim = c(x_start, x_end)) +
  guides(fill = "none", color = guide_legend(override.aes = list(alpha = 1, linewidth = 1, size = 4))) +
  theme_base_plot

# ------------------------------------------------------------------------------
# 4. CONSTRUCT MAP PANEL
# ------------------------------------------------------------------------------
world  <- ne_countries(scale = "medium", returnclass = "sf")
europe <- subset(world, continent == "Europe")

lon_min <- -19
lon_max <-  1
lat_min <- 26
lat_max <-  57.5

europe_map <- ggplot() +
  geom_sf(data = europe, fill = "gray20", color = "gray20") +
  geom_segment(aes(x = lon_max, xend = lon_max, y = lat_min, yend = lat_max), color = "black", linewidth = 1) +
  geom_segment(aes(x = lon_min, xend = lon_max, y = lat_min, yend = lat_min), color = "black", linewidth = 1) +
  coord_sf(xlim = c(lon_min, lon_max), ylim = c(lat_min, lat_max), expand = FALSE) +
  theme_void() +
  theme(panel.background = element_rect(fill = "white", color = NA))

# ------------------------------------------------------------------------------
# 5. ASSEMBLE COMPOSITE FIGURES & EXPORT
# ------------------------------------------------------------------------------
message("Assembling composite plots (Trends + Map)...")

# Seasonal + Map
combined_seasonal_map <- seasonal_plot_base + europe_map +
  plot_layout(ncol = 2, widths = c(2.2, 1)) +
  plot_annotation(theme = theme(plot.title = element_text(hjust = 0.3, size = 25, margin = margin(b = 10))))

ggsave("figures/publication/fig_02_seasonal_composite.png", plot = combined_seasonal_map, 
       width = 14, height = 8, dpi = 300, bg = "white")

# Historical + Map
combined_historical_map <- historical_plot_base + europe_map +
  plot_layout(ncol = 2, widths = c(2.2, 1)) +
  plot_annotation(theme = theme(plot.title = element_text(hjust = 0.3, size = 25, margin = margin(b = 10))))

ggsave("figures/exploratory/fig_S1_historical_composite.png", plot = combined_historical_map, 
       width = 14, height = 8, dpi = 300, bg = "white")

# ------------------------------------------------------------------------------
# 6. FACETED PLOTS (SUPPLEMENTARY/REVIEWER REQUESTS)
# ------------------------------------------------------------------------------
message("Applying faceted aesthetics for reviewer requests...")

theme_facet <- theme(
  strip.text = element_text(face = "bold", size = 14),
  strip.background = element_rect(fill = "white", colour = NA),
  legend.position = "none"
)

seasonal_plot_faceted <- seasonal_plot_base + facet_wrap(~ species, ncol = 1, scales = "free_y", axes = "all_x") + theme_facet
historical_plot_faceted <- historical_plot_base + facet_wrap(~ species, ncol = 1, scales = "free_y", axes = "all_x") + theme_facet

ggsave("figures/exploratory/fig_S2_seasonal_faceted.png", plot = seasonal_plot_faceted, width = 10, height = 12, dpi = 300, bg = "white")
ggsave("figures/exploratory/fig_S3_historical_faceted.png", plot = historical_plot_faceted, width = 10, height = 12, dpi = 300, bg = "white")

# ------------------------------------------------------------------------------
# 7. REVISED BIOLOGICAL HOVMÖLLER DIAGRAM (TENSOR PRODUCT)
# ------------------------------------------------------------------------------
message("Generating inverted Hovmöller matrices via Tensor Product smooths...")

df_all_filtered <- df_all |> filter(year >= 2014 & year <= 2025)

generar_hov_grid_inverted <- function(datos_especie) {
  mod <- qgam(decimalLatitude ~ te(yday, decimalYear, bs = c("cc", "tp")), data = datos_especie, qu = 0.5)
  grid <- expand.grid(yday = seq(1, 365, length.out = 100), decimalYear = seq(2014, 2025, length.out = 100))
  grid$pred_lat <- predict(mod, newdata = grid)
  grid$species <- unique(datos_especie$species)
  return(grid)
}

grid_hov_all <- bind_rows(
  generar_hov_grid_inverted(df_all_filtered |> filter(species == "Physalia")),
  generar_hov_grid_inverted(df_all_filtered |> filter(species == "Velella")),
  generar_hov_grid_inverted(df_all_filtered |> filter(species == "Neutral Neuston"))
)

hovmoller_bio_plot_inverted <- ggplot(grid_hov_all, aes(x = decimalYear, y = yday, fill = pred_lat)) +
  geom_tile() + 
  facet_wrap(~ species, ncol = 1, axes = "all_x") + 
  scale_fill_viridis_c(option = "turbo", name = "Latitude (°N)") +
  scale_x_continuous(breaks = seq(2014, 2025, by = 1), expand = c(0, 0), name = "Year") +
  scale_y_continuous(breaks = seq(15, 345, length.out = 12), labels = month.abb, expand = c(0, 0), name = "Month") +
  theme_minimal(base_size = 16) +
  theme(
    strip.text = element_text(face = "bold", size = 16),
    strip.background = element_rect(fill = "white", colour = NA),
    axis.text.x = element_text(angle = 45, hjust = 1, colour = "black"),
    axis.text.y = element_text(colour = "black"),
    panel.grid = element_blank(),
    axis.ticks = element_line(linewidth = 0.5),
    axis.line = element_line(linewidth = 0.5)
  )

ggsave("figures/exploratory/fig_S4_hovmoller_inverted.png", plot = hovmoller_bio_plot_inverted, 
       width = 10, height = 12, dpi = 300, bg = "white")

message("All publication figures (Composite + Faceted + Hovmoller) successfully generated and exported.")
